window.esdocSearchIndex = [
  [
    "trek/src/config.js~config",
    "class/src/Config.js~Config.html",
    "<span>Config</span> <span class=\"search-result-import-path\">trek/src/Config.js</span>",
    "class"
  ],
  [
    "trek/src/context.js~context",
    "class/src/Context.js~Context.html",
    "<span>Context</span> <span class=\"search-result-import-path\">trek/src/Context.js</span>",
    "class"
  ],
  [
    "trek/src/engine.js~engine",
    "class/src/Engine.js~Engine.html",
    "<span>Engine</span> <span class=\"search-result-import-path\">trek/src/Engine.js</span>",
    "class"
  ],
  [
    "trek/src/paths.js~paths",
    "class/src/Paths.js~Paths.html",
    "<span>Paths</span> <span class=\"search-result-import-path\">trek/src/Paths.js</span>",
    "class"
  ],
  [
    "trek/src/trek.js~trek",
    "class/src/Trek.js~Trek.html",
    "<span>Trek</span> <span class=\"search-result-import-path\">trek/src/Trek.js</span>",
    "class"
  ],
  [
    "trek/src/view.js~view",
    "class/src/View.js~View.html",
    "<span>View</span> <span class=\"search-result-import-path\">trek/src/View.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/test/Config.test.js.html#lineNumber6",
    "Config",
    "test"
  ],
  [
    "",
    "test-file/test/Config.test.js.html#lineNumber17",
    "Config #get()",
    "test"
  ],
  [
    "",
    "test-file/test/Config.test.js.html#lineNumber18",
    "Config #get() should return $PATH from env",
    "test"
  ],
  [
    "",
    "test-file/test/Config.test.js.html#lineNumber23",
    "Config #get() should return a secret key from secrets.yml",
    "test"
  ],
  [
    "",
    "test-file/test/Config.test.js.html#lineNumber29",
    "Config #set()",
    "test"
  ],
  [
    "",
    "test-file/test/Config.test.js.html#lineNumber30",
    "Config #set() should return new value when reseting",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber12",
    "Engine",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber87",
    "Engine #*render()",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber96",
    "Engine #*render() should render the template",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber47",
    "Engine #config",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber49",
    "Engine #config should return a Config instance",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber195",
    "Engine #context",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber239",
    "Engine #context #json()",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber241",
    "Engine #context #json() should response with json",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber260",
    "Engine #context #jsonp()",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber262",
    "Engine #context #jsonp() should response with jsonp",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber201",
    "Engine #context #render()",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber203",
    "Engine #context #render() should render template",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber221",
    "Engine #context #sendFile()",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber223",
    "Engine #context #sendFile() should send a file",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber282",
    "Engine #context #xhr",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber284",
    "Engine #context #xhr should return true when X-Requested-With is xmlhttprequest",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber25",
    "Engine #env",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber27",
    "Engine #env should return `Trek.env`",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber67",
    "Engine #path",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber69",
    "Engine #path should return empty string when parent is null",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber55",
    "Engine #paths",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber61",
    "Engine #paths should equal to #config.paths",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber57",
    "Engine #paths should return a Paths instance",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber33",
    "Engine #rootPath",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber40",
    "Engine #rootPath should get a path",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber35",
    "Engine #rootPath should set a path",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber75",
    "Engine #run()",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber77",
    "Engine #run() should be a function",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber81",
    "Engine #run() should return a promise",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber115",
    "Engine http verbs, get(), post()..., match(), all()",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber133",
    "Engine http verbs, get(), post()..., match(), all() #all()",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber117",
    "Engine http verbs, get(), post()..., match(), all() #match()",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber151",
    "Engine serve static",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber163",
    "Engine serve static #favicon()",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber153",
    "Engine serve static #index()",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber183",
    "Engine serve static #serveDir()",
    "test"
  ],
  [
    "",
    "test-file/test/Engine.test.js.html#lineNumber173",
    "Engine serve static #static()",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber5",
    "Paths",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber14",
    "Paths #formats",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber15",
    "Paths #formats should return `toml|json|js|yml`",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber20",
    "Paths #get()",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber42",
    "Paths #get() should return `config/.env.test` from `config/.env`",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber38",
    "Paths #get() should return `config/app.test.json` from `config/app.env`",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber34",
    "Paths #get() should return `config/app.toml` from `config/app`",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber46",
    "Paths #get() should return `config/routes.js` from `config/routes`",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber22",
    "Paths #get() should return an absolute path",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber30",
    "Paths #get() should return an array from `app/services`",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber26",
    "Paths #get() should return app from `app`",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber8",
    "Paths #root",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber9",
    "Paths #root should return a path",
    "test"
  ],
  [
    "",
    "test-file/test/Paths.test.js.html#lineNumber52",
    "Paths #set()",
    "test"
  ],
  [
    "",
    "test-file/test/hello-world.test.js.html#lineNumber5",
    "Trek",
    "test"
  ],
  [
    "",
    "test-file/test/hello-world.test.js.html#lineNumber34",
    "Trek comments resources",
    "test"
  ],
  [
    "",
    "test-file/test/hello-world.test.js.html#lineNumber54",
    "Trek comments resources DELETE /comments",
    "test"
  ],
  [
    "",
    "test-file/test/hello-world.test.js.html#lineNumber42",
    "Trek comments resources GET /comments",
    "test"
  ],
  [
    "",
    "test-file/test/hello-world.test.js.html#lineNumber60",
    "Trek comments resources GET /comments/new",
    "test"
  ],
  [
    "",
    "test-file/test/hello-world.test.js.html#lineNumber48",
    "Trek comments resources POST /comments",
    "test"
  ],
  [
    "",
    "test-file/test/hello-world.test.js.html#lineNumber16",
    "Trek hello world",
    "test"
  ],
  [
    "src/config.js",
    "file/src/Config.js.html",
    "src/Config.js",
    "file"
  ],
  [
    "src/config.js~config#compile",
    "class/src/Config.js~Config.html#instance-method-compile",
    "src/Config.js~Config#compile",
    "method"
  ],
  [
    "src/config.js~config#constructor",
    "class/src/Config.js~Config.html#instance-constructor-constructor",
    "src/Config.js~Config#constructor",
    "method"
  ],
  [
    "src/config.js~config#dotenv",
    "class/src/Config.js~Config.html#instance-method-dotenv",
    "src/Config.js~Config#dotenv",
    "method"
  ],
  [
    "src/config.js~config#get",
    "class/src/Config.js~Config.html#instance-method-get",
    "src/Config.js~Config#get",
    "method"
  ],
  [
    "src/config.js~config#list",
    "class/src/Config.js~Config.html#instance-member-list",
    "src/Config.js~Config#list",
    "member"
  ],
  [
    "src/config.js~config#load",
    "class/src/Config.js~Config.html#instance-method-load",
    "src/Config.js~Config#load",
    "method"
  ],
  [
    "src/config.js~config#loadlist",
    "class/src/Config.js~Config.html#instance-method-loadList",
    "src/Config.js~Config#loadList",
    "method"
  ],
  [
    "src/config.js~config#parse",
    "class/src/Config.js~Config.html#instance-method-parse",
    "src/Config.js~Config#parse",
    "method"
  ],
  [
    "src/config.js~config#parsers",
    "class/src/Config.js~Config.html#instance-member-parsers",
    "src/Config.js~Config#parsers",
    "member"
  ],
  [
    "src/config.js~config#paths",
    "class/src/Config.js~Config.html#instance-member-paths",
    "src/Config.js~Config#paths",
    "member"
  ],
  [
    "src/config.js~config#render",
    "class/src/Config.js~Config.html#instance-method-render",
    "src/Config.js~Config#render",
    "method"
  ],
  [
    "src/config.js~config#root",
    "class/src/Config.js~Config.html#instance-member-root",
    "src/Config.js~Config#root",
    "member"
  ],
  [
    "src/config.js~config#separator",
    "class/src/Config.js~Config.html#instance-member-separator",
    "src/Config.js~Config#separator",
    "member"
  ],
  [
    "src/config.js~config#set",
    "class/src/Config.js~Config.html#instance-method-set",
    "src/Config.js~Config#set",
    "method"
  ],
  [
    "src/config.js~config#stores",
    "class/src/Config.js~Config.html#instance-member-stores",
    "src/Config.js~Config#stores",
    "member"
  ],
  [
    "src/context.js",
    "file/src/Context.js.html",
    "src/Context.js",
    "file"
  ],
  [
    "src/context.js~context#body",
    "class/src/Context.js~Context.html#instance-member-body",
    "src/Context.js~Context#body",
    "member"
  ],
  [
    "src/context.js~context#config",
    "class/src/Context.js~Context.html#instance-get-config",
    "src/Context.js~Context#config",
    "member"
  ],
  [
    "src/context.js~context#constructor",
    "class/src/Context.js~Context.html#instance-constructor-constructor",
    "src/Context.js~Context#constructor",
    "method"
  ],
  [
    "src/context.js~context#getservice",
    "class/src/Context.js~Context.html#instance-method-getService",
    "src/Context.js~Context#getService",
    "method"
  ],
  [
    "src/context.js~context#json",
    "class/src/Context.js~Context.html#instance-method-json",
    "src/Context.js~Context#json",
    "method"
  ],
  [
    "src/context.js~context#jsonp",
    "class/src/Context.js~Context.html#instance-method-jsonp",
    "src/Context.js~Context#jsonp",
    "method"
  ],
  [
    "src/context.js~context#logger",
    "class/src/Context.js~Context.html#instance-get-logger",
    "src/Context.js~Context#logger",
    "member"
  ],
  [
    "src/context.js~context#params",
    "class/src/Context.js~Context.html#instance-member-params",
    "src/Context.js~Context#params",
    "member"
  ],
  [
    "src/context.js~context#render",
    "class/src/Context.js~Context.html#instance-method-render",
    "src/Context.js~Context#render",
    "method"
  ],
  [
    "src/context.js~context#sendfile",
    "class/src/Context.js~Context.html#instance-method-sendFile",
    "src/Context.js~Context#sendFile",
    "method"
  ],
  [
    "src/context.js~context#type",
    "class/src/Context.js~Context.html#instance-member-type",
    "src/Context.js~Context#type",
    "member"
  ],
  [
    "src/context.js~context#xhr",
    "class/src/Context.js~Context.html#instance-get-xhr",
    "src/Context.js~Context#xhr",
    "member"
  ],
  [
    "src/engine.js",
    "file/src/Engine.js.html",
    "src/Engine.js",
    "file"
  ],
  [
    "src/engine.js~engine#all",
    "class/src/Engine.js~Engine.html#instance-method-all",
    "src/Engine.js~Engine#all",
    "method"
  ],
  [
    "src/engine.js~engine#body",
    "class/src/Engine.js~Engine.html#instance-member-body",
    "src/Engine.js~Engine#body",
    "member"
  ],
  [
    "src/engine.js~engine#bootstrap",
    "class/src/Engine.js~Engine.html#instance-method-bootstrap",
    "src/Engine.js~Engine#bootstrap",
    "method"
  ],
  [
    "src/engine.js~engine#cache",
    "class/src/Engine.js~Engine.html#instance-member-cache",
    "src/Engine.js~Engine#cache",
    "member"
  ],
  [
    "src/engine.js~engine#config",
    "class/src/Engine.js~Engine.html#instance-member-config",
    "src/Engine.js~Engine#config",
    "member"
  ],
  [
    "src/engine.js~engine#constructor",
    "class/src/Engine.js~Engine.html#instance-constructor-constructor",
    "src/Engine.js~Engine#constructor",
    "method"
  ],
  [
    "src/engine.js~engine#context",
    "class/src/Engine.js~Engine.html#instance-member-context",
    "src/Engine.js~Engine#context",
    "member"
  ],
  [
    "src/engine.js~engine#engine",
    "class/src/Engine.js~Engine.html#instance-method-engine",
    "src/Engine.js~Engine#engine",
    "method"
  ],
  [
    "src/engine.js~engine#engines",
    "class/src/Engine.js~Engine.html#instance-member-engines",
    "src/Engine.js~Engine#engines",
    "member"
  ],
  [
    "src/engine.js~engine#env",
    "class/src/Engine.js~Engine.html#instance-member-env",
    "src/Engine.js~Engine#env",
    "member"
  ],
  [
    "src/engine.js~engine#favicon",
    "class/src/Engine.js~Engine.html#instance-method-favicon",
    "src/Engine.js~Engine#favicon",
    "method"
  ],
  [
    "src/engine.js~engine#getservice",
    "class/src/Engine.js~Engine.html#instance-method-getService",
    "src/Engine.js~Engine#getService",
    "method"
  ],
  [
    "src/engine.js~engine#index",
    "class/src/Engine.js~Engine.html#instance-method-index",
    "src/Engine.js~Engine#index",
    "method"
  ],
  [
    "src/engine.js~engine#initialized",
    "class/src/Engine.js~Engine.html#instance-member-initialized",
    "src/Engine.js~Engine#initialized",
    "member"
  ],
  [
    "src/engine.js~engine#isbooted",
    "class/src/Engine.js~Engine.html#instance-member-isBooted",
    "src/Engine.js~Engine#isBooted",
    "member"
  ],
  [
    "src/engine.js~engine#loadservices",
    "class/src/Engine.js~Engine.html#instance-method-loadServices",
    "src/Engine.js~Engine#loadServices",
    "method"
  ],
  [
    "src/engine.js~engine#logger",
    "class/src/Engine.js~Engine.html#instance-get-logger",
    "src/Engine.js~Engine#logger",
    "member"
  ],
  [
    "src/engine.js~engine#match",
    "class/src/Engine.js~Engine.html#instance-method-match",
    "src/Engine.js~Engine#match",
    "method"
  ],
  [
    "src/engine.js~engine#mountpath",
    "class/src/Engine.js~Engine.html#instance-member-mountpath",
    "src/Engine.js~Engine#mountpath",
    "member"
  ],
  [
    "src/engine.js~engine#path",
    "class/src/Engine.js~Engine.html#instance-get-path",
    "src/Engine.js~Engine#path",
    "member"
  ],
  [
    "src/engine.js~engine#paths",
    "class/src/Engine.js~Engine.html#instance-get-paths",
    "src/Engine.js~Engine#paths",
    "member"
  ],
  [
    "src/engine.js~engine#render",
    "class/src/Engine.js~Engine.html#instance-method-render",
    "src/Engine.js~Engine#render",
    "method"
  ],
  [
    "src/engine.js~engine#rootpath",
    "class/src/Engine.js~Engine.html#instance-get-rootPath",
    "src/Engine.js~Engine#rootPath",
    "member"
  ],
  [
    "src/engine.js~engine#rootpath",
    "class/src/Engine.js~Engine.html#instance-set-rootPath",
    "src/Engine.js~Engine#rootPath",
    "member"
  ],
  [
    "src/engine.js~engine#routemapper",
    "class/src/Engine.js~Engine.html#instance-get-routeMapper",
    "src/Engine.js~Engine#routeMapper",
    "member"
  ],
  [
    "src/engine.js~engine#router",
    "class/src/Engine.js~Engine.html#instance-member-router",
    "src/Engine.js~Engine#router",
    "member"
  ],
  [
    "src/engine.js~engine#run",
    "class/src/Engine.js~Engine.html#instance-method-run",
    "src/Engine.js~Engine#run",
    "method"
  ],
  [
    "src/engine.js~engine#servedir",
    "class/src/Engine.js~Engine.html#instance-method-serveDir",
    "src/Engine.js~Engine#serveDir",
    "method"
  ],
  [
    "src/engine.js~engine#servefile",
    "class/src/Engine.js~Engine.html#instance-method-serveFile",
    "src/Engine.js~Engine#serveFile",
    "method"
  ],
  [
    "src/engine.js~engine#server",
    "class/src/Engine.js~Engine.html#instance-member-server",
    "src/Engine.js~Engine#server",
    "member"
  ],
  [
    "src/engine.js~engine#services",
    "class/src/Engine.js~Engine.html#instance-get-services",
    "src/Engine.js~Engine#services",
    "member"
  ],
  [
    "src/engine.js~engine#set",
    "class/src/Engine.js~Engine.html#instance-method-set",
    "src/Engine.js~Engine#set",
    "method"
  ],
  [
    "src/engine.js~engine#setservice",
    "class/src/Engine.js~Engine.html#instance-method-setService",
    "src/Engine.js~Engine#setService",
    "method"
  ],
  [
    "src/engine.js~engine#state",
    "class/src/Engine.js~Engine.html#instance-member-state",
    "src/Engine.js~Engine#state",
    "member"
  ],
  [
    "src/engine.js~engine#static",
    "class/src/Engine.js~Engine.html#instance-method-static",
    "src/Engine.js~Engine#static",
    "method"
  ],
  [
    "src/parsers.js",
    "file/src/Parsers.js.html",
    "src/Parsers.js",
    "file"
  ],
  [
    "src/paths.js",
    "file/src/Paths.js.html",
    "src/Paths.js",
    "file"
  ],
  [
    "src/paths.js~paths#blueprint",
    "class/src/Paths.js~Paths.html#instance-member-blueprint",
    "src/Paths.js~Paths#blueprint",
    "member"
  ],
  [
    "src/paths.js~paths#constructor",
    "class/src/Paths.js~Paths.html#instance-constructor-constructor",
    "src/Paths.js~Paths#constructor",
    "method"
  ],
  [
    "src/paths.js~paths#formats",
    "class/src/Paths.js~Paths.html#instance-member-formats",
    "src/Paths.js~Paths#formats",
    "member"
  ],
  [
    "src/paths.js~paths#get",
    "class/src/Paths.js~Paths.html#instance-method-get",
    "src/Paths.js~Paths#get",
    "method"
  ],
  [
    "src/paths.js~paths#getpattern",
    "class/src/Paths.js~Paths.html#instance-method-getPattern",
    "src/Paths.js~Paths#getPattern",
    "method"
  ],
  [
    "src/paths.js~paths#root",
    "class/src/Paths.js~Paths.html#instance-member-root",
    "src/Paths.js~Paths#root",
    "member"
  ],
  [
    "src/paths.js~paths#set",
    "class/src/Paths.js~Paths.html#instance-method-set",
    "src/Paths.js~Paths#set",
    "method"
  ],
  [
    "src/stack.js",
    "file/src/Stack.js.html",
    "src/Stack.js",
    "file"
  ],
  [
    "src/trek.js",
    "file/src/Trek.js.html",
    "src/Trek.js",
    "file"
  ],
  [
    "src/trek.js~trek.env",
    "class/src/Trek.js~Trek.html#static-get-env",
    "src/Trek.js~Trek.env",
    "member"
  ],
  [
    "src/trek.js~trek.isdevelopment",
    "class/src/Trek.js~Trek.html#static-get-isDevelopment",
    "src/Trek.js~Trek.isDevelopment",
    "member"
  ],
  [
    "src/trek.js~trek.isproduction",
    "class/src/Trek.js~Trek.html#static-get-isProduction",
    "src/Trek.js~Trek.isProduction",
    "member"
  ],
  [
    "src/trek.js~trek.istest",
    "class/src/Trek.js~Trek.html#static-get-isTest",
    "src/Trek.js~Trek.isTest",
    "member"
  ],
  [
    "src/trek.js~trek.logger",
    "class/src/Trek.js~Trek.html#static-get-logger",
    "src/Trek.js~Trek.logger",
    "member"
  ],
  [
    "src/trek.js~trek.logger",
    "class/src/Trek.js~Trek.html#static-set-logger",
    "src/Trek.js~Trek.logger",
    "member"
  ],
  [
    "src/trek.js~trek.package",
    "class/src/Trek.js~Trek.html#static-get-package",
    "src/Trek.js~Trek.package",
    "member"
  ],
  [
    "src/trek.js~trek.version",
    "class/src/Trek.js~Trek.html#static-get-version",
    "src/Trek.js~Trek.version",
    "member"
  ],
  [
    "src/view.js",
    "file/src/View.js.html",
    "src/View.js",
    "file"
  ],
  [
    "src/view.js~view#constructor",
    "class/src/View.js~View.html#instance-constructor-constructor",
    "src/View.js~View#constructor",
    "method"
  ],
  [
    "src/view.js~view#defaultengine",
    "class/src/View.js~View.html#instance-member-defaultEngine",
    "src/View.js~View#defaultEngine",
    "member"
  ],
  [
    "src/view.js~view#engine",
    "class/src/View.js~View.html#instance-member-engine",
    "src/View.js~View#engine",
    "member"
  ],
  [
    "src/view.js~view#ext",
    "class/src/View.js~View.html#instance-member-ext",
    "src/View.js~View#ext",
    "member"
  ],
  [
    "src/view.js~view#fetchpath",
    "class/src/View.js~View.html#instance-method-fetchPath",
    "src/View.js~View#fetchPath",
    "method"
  ],
  [
    "src/view.js~view#filename",
    "class/src/View.js~View.html#instance-member-fileName",
    "src/View.js~View#fileName",
    "member"
  ],
  [
    "src/view.js~view#lookup",
    "class/src/View.js~View.html#instance-method-lookup",
    "src/View.js~View#lookup",
    "method"
  ],
  [
    "src/view.js~view#name",
    "class/src/View.js~View.html#instance-member-name",
    "src/View.js~View#name",
    "member"
  ],
  [
    "src/view.js~view#render",
    "class/src/View.js~View.html#instance-method-render",
    "src/View.js~View#render",
    "method"
  ],
  [
    "src/view.js~view#resolve",
    "class/src/View.js~View.html#instance-method-resolve",
    "src/View.js~View#resolve",
    "method"
  ],
  [
    "src/view.js~view#root",
    "class/src/View.js~View.html#instance-member-root",
    "src/View.js~View#root",
    "member"
  ],
  [
    "test/config.test.js",
    "test-file/test/Config.test.js.html",
    "test/Config.test.js",
    "testFile"
  ],
  [
    "test/engine.test.js",
    "test-file/test/Engine.test.js.html",
    "test/Engine.test.js",
    "testFile"
  ],
  [
    "test/paths.test.js",
    "test-file/test/Paths.test.js.html",
    "test/Paths.test.js",
    "testFile"
  ],
  [
    "test/hello-world.test.js",
    "test-file/test/hello-world.test.js.html",
    "test/hello-world.test.js",
    "testFile"
  ]
]